// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEBAPIKEY'] as String,
    appId: dotenv.env['WEBAPPID'] as String,
    messagingSenderId: dotenv.env['MESSANGINGSENDERID'] as String,
    projectId: dotenv.env['PROJECTID'] as String,
    authDomain: 'read-ease-app.firebaseapp.com',
    storageBucket: 'read-ease-app.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROIDAPIKEY'] as String,
    appId: dotenv.env['ANDROIDAPPID'] as String,
    messagingSenderId: dotenv.env['MESSANGINGSENDERID'] as String,
    projectId: dotenv.env['PROJECTID'] as String,
    storageBucket: 'read-ease-app.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOSAPIKEY'] as String,
    appId: dotenv.env['IOSAPPID'] as String,
    messagingSenderId: dotenv.env['MESSANGINGSENDERID'] as String,
    projectId: dotenv.env['PROJECTID'] as String,
    storageBucket: 'read-ease-app.firebasestorage.app',
    iosBundleId: 'com.example.readEaseApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['IOSAPIKEY'] as String,
    appId: dotenv.env['IOSAPPID'] as String,
    messagingSenderId: dotenv.env['MESSANGINGSENDERID'] as String,
    projectId: dotenv.env['PROJECTID'] as String,
    storageBucket: 'read-ease-app.firebasestorage.app',
    iosBundleId: 'com.example.readEaseApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WEBAPIKEY'] as String,
    appId: dotenv.env['WINDOWSAPPID'] as String,
    messagingSenderId: dotenv.env['MESSANGINGSENDERID'] as String,
    projectId: dotenv.env['PROJECTID'] as String,
    authDomain: 'read-ease-app.firebaseapp.com',
    storageBucket: 'read-ease-app.firebasestorage.app',
  );
}
